### ISSUE TITLE
Look for uses of `as` for numeric conversions

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/rust-ga#38]
We imported the `easy_cast` crate in the `push` package, and that might be useful in other places where I did less than wonderful conversions using `as`.

**Comment by JustusFluegel** [comment]
So I had a look at it, there is a clippy lint for as conversions ( of course there is xD ). We don't seem to be using any more as conversions in the `push` crate at least.

**Comment by NicMcPhee** [comment]
Thanks!

I kinda suspect that I used `as` in the early days of some of the other packages in `rust-ga`, though. I haven't looked, though. Since Clippy fusses about it, it's possible that they've all been dealt with, but it's possible that "dealt with" might be telling Clippy to ignore some uses of `as`.

**Comment by JustusFluegel** [comment]
yea the lint I enabled is allow by default tho, so I am reasonably sure we didn't explicitly allow it anywhere
