### ISSUE TITLE
Add examples to CI as smoke tests

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/rust-ga#52]
We don't want to have these run a long time, but we could set them up to do things like 100 individuals for 10 generations just to ensure that everything builds and runs. Maybe this only needs to happen when merging to `main`.

**Comment by JustusFluegel** [comment]
@NicMcPhee let's close this #73 resolved this.

**Comment by NicMcPhee** [comment]
Agreed – thanks for taking care of that and noticing that this can be closed.
